import * as fs from "fs-extra"
import * as path from "path"
import * as os from "os"
import { execa } from "execa"
import chalk from "chalk"
import { log, section, table } from "../utils/terminal"
import {
  getGitCommitCount,
  getGitUserEmail,
  getProjectName,
  runNpmAudit,
} from "../utils/system"
import { validateEnvStructure } from "../utils/env"

interface ShareOptions {
  context?: boolean
}

export async function shareCommand(options: ShareOptions): Promise<void> {
  const cwd = process.cwd()

  console.log()
  console.log(chalk.bold("  📤 OnboardAI — Share Context"))
  console.log(chalk.gray("  ─────────────────────────────────────────"))
  console.log()

  const [gitCommits, gitEmail, projectName, audit, envStatus] = await Promise.all([
    getGitCommitCount(cwd),
    getGitUserEmail(cwd),
    getProjectName(cwd),
    runNpmAudit(cwd),
    validateEnvStructure(cwd),
  ])

  // Load onboarding profile
  const profilePath = path.join(cwd, ".onboardai.json")
  let profile: { role?: string; team?: string; name?: string; setupAt?: string } = {}
  if (await fs.pathExists(profilePath)) {
    profile = await fs.readJson(profilePath)
  }

  // Get recent git log
  const recentCommits = await getRecentCommits(cwd, 5)
  const blockers = await detectBlockers(cwd)

  const contextSummary = buildContextSummary({
    name: profile.name || gitEmail,
    role: profile.role,
    team: profile.team,
    projectName,
    gitCommits,
    recentCommits,
    vulnerabilities: audit.vulnerabilities,
    envConfigured: envStatus.configured,
    envTotal: envStatus.total,
    missingEnvKeys: envStatus.missing,
    blockers,
    setupAt: profile.setupAt,
  })

  if (options.context) {
    section("Context Summary")
    console.log()
    console.log(chalk.gray("  " + "─".repeat(56)))
    contextSummary.split("\n").forEach((line) => console.log("  " + line))
    console.log(chalk.gray("  " + "─".repeat(56)))
    console.log()

    const copied = await copyToClipboard(contextSummary)
    if (copied) {
      log.success("Context summary copied to clipboard!")
    } else {
      log.info("Copy the summary above and share it with your team.")
    }

    // Also save to file
    const sharePath = path.join(cwd, "onboarding-context.md")
    await fs.writeFile(sharePath, contextSummary)
    log.success(`Saved to ${chalk.cyan("onboarding-context.md")}`)
  } else {
    log.info("Use `onboardai share --context` to generate a shareable context summary.")
  }

  console.log()
}

function buildContextSummary(data: {
  name: string
  role?: string
  team?: string
  projectName: string
  gitCommits: number
  recentCommits: string[]
  vulnerabilities: number
  envConfigured: number
  envTotal: number
  missingEnvKeys: string[]
  blockers: string[]
  setupAt?: string
}): string {
  const date = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
  const lines = [
    `# Onboarding Context — ${data.name || "New Developer"}`,
    `Date: ${date}`,
    "",
    "## Who I am",
    `- **Name:** ${data.name || "—"}`,
    `- **Role:** ${data.role || "—"}`,
    `- **Team:** ${data.team || "—"}`,
    `- **Project:** ${data.projectName}`,
    "",
    "## Current status",
    `- **Setup started:** ${data.setupAt ? new Date(data.setupAt).toLocaleDateString() : "—"}`,
    `- **Git commits made:** ${data.gitCommits}`,
    `- **Env variables configured:** ${data.envConfigured}/${data.envTotal}`,
    `- **Security vulnerabilities:** ${data.vulnerabilities}`,
    "",
  ]

  if (data.recentCommits.length > 0) {
    lines.push("## Recent commits")
    data.recentCommits.forEach((c) => lines.push(`- ${c}`))
    lines.push("")
  }

  if (data.blockers.length > 0) {
    lines.push("## Blockers / open questions")
    data.blockers.forEach((b) => lines.push(`- ${b}`))
    lines.push("")
  } else {
    lines.push("## Blockers / open questions")
    lines.push("- None currently — making good progress!")
    lines.push("")
  }

  if (data.missingEnvKeys.length > 0) {
    lines.push("## Pending setup")
    lines.push(`Missing environment variables that need values: ${data.missingEnvKeys.join(", ")}`)
    lines.push("")
  }

  lines.push("---")
  lines.push("*Generated by OnboardAI CLI*")

  return lines.join("\n")
}

async function getRecentCommits(cwd: string, n: number): Promise<string[]> {
  try {
    const { stdout } = await execa("git", ["log", `--oneline`, `-${n}`], { cwd })
    return stdout.trim().split("\n").filter(Boolean)
  } catch {
    return []
  }
}

async function detectBlockers(cwd: string): Promise<string[]> {
  const blockers: string[] = []

  // Check for TODO comments in recent files
  try {
    const { stdout } = await execa("git", ["diff", "--name-only", "HEAD~3..HEAD"], { cwd })
    const changedFiles = stdout.trim().split("\n").filter(Boolean)

    for (const file of changedFiles.slice(0, 5)) {
      const filePath = path.join(cwd, file)
      if (!(await fs.pathExists(filePath))) continue
      const content = await fs.readFile(filePath, "utf8").catch(() => "")
      const hasTodo = /\bTODO\b|\bFIXME\b|\bHACK\b/i.test(content)
      if (hasTodo) {
        blockers.push(`Unresolved TODO/FIXME in ${file}`)
        break
      }
    }
  } catch {
    // no git history
  }

  return blockers
}

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    const platform = process.platform
    if (platform === "darwin") {
      await execa("pbcopy", [], { input: text })
      return true
    } else if (platform === "win32") {
      await execa("clip", [], { input: text })
      return true
    } else {
      // Linux — try xclip or xsel
      try {
        await execa("xclip", ["-selection", "clipboard"], { input: text })
        return true
      } catch {
        await execa("xsel", ["--clipboard", "--input"], { input: text })
        return true
      }
    }
  } catch {
    return false
  }
}
